services:
  web:
    container_name: beepitron-webui-demo
    build: webui-demo
    volumes: 
      - ./webui-demo:/app
    ports:
      - "80:80"
    environment:
      - DOCKER=true


  cv:
    container_name: beepitron-cv
    build: cv
    runtime: nvidia
    ports:
      - "8001:8001"
    volumes: 
      - ./cv:/app
      - ./config:/config
      
    network_mode: "host" 
    environment:
      - DOCKER=true

  robot:
    container_name: beepitron-robot
    build: robot
    ports:
      - "48569:48569"
      - "8002:8002"
    volumes:
      - ./robot:/app
      - ./config:/config
    environment:
      - DOCKER=true
  # logger:
  #   container_name: beepitron-logger
  #   build: log-db
  #   ports:
  #     - "8003:8003"
  #   volumes:
  #     - ./log-db:/app
  #     - ./config:/config